class AppGlobal {
    url = {
        index:'/',
        tian_qi_xia_zai:'https://wx.wuminmin.top/qyrd/tian_qi_xia_zai',
        uploadimg:'https://wx.wuminmin.top/qyrd/upload_img',
        rd_xia_zai_tabs_by_ban_kuai:'https://wx.wuminmin.top/qyrd/rd_xia_zai_tabs_by_ban_kuai',
        rd_updata:'https://wx.wuminmin.top/qyrd/rd_updata',
        rd_xia_zai:'https://wx.wuminmin.top/qyrd/rd_xia_zai',
        rd_xia_zai_by_lan_mu:'https://wx.wuminmin.top/qyrd/rd_xia_zai_by_lan_mu',
        rd_xia_zai_by_tittle:'https://wx.wuminmin.top/qyrd/rd_xia_zai_by_tittle',
        rd_xia_zai_time_by_tittle:'https://wx.wuminmin.top/qyrd/rd_xia_zai_time_by_tittle',
        首页滚动图片1:'https://wx.wuminmin.top/qyrd/image?id=首页滚动图片1',
        首页滚动图片2:'https://wx.wuminmin.top/qyrd/image?id=首页滚动图片2',
        首页滚动图片3:'https://wx.wuminmin.top/qyrd/image?id=首页滚动图片3',
        首页滚动图片4:'https://wx.wuminmin.top/qyrd/image?id=首页滚动图片4',
        首页滚动图片5:'https://wx.wuminmin.top/qyrd/image?id=首页滚动图片5',
        首页工程案例1:'https://wx.wuminmin.top/qyrd/image?id=工程案例1',
        首页工程案例2:'https://wx.wuminmin.top/qyrd/image?id=工程案例2',
        首页工程案例3:'https://wx.wuminmin.top/qyrd/image?id=工程案例3',
        首页工程案例4:'https://wx.wuminmin.top/qyrd/image?id=工程案例4',
        首页工程案例5:'https://wx.wuminmin.top/qyrd/image?id=工程案例5',
        首页中间横幅图片1:'https://wx.wuminmin.top/qyrd/image?id=首页中间横幅图片1',
        首页中间横幅图片2:'https://wx.wuminmin.top/qyrd/image?id=首页中间横幅图片2',
        首页中间横幅图片3:'https://wx.wuminmin.top/qyrd/image?id=首页中间横幅图片3',
        产品中心滚动图片1:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片1',
        产品中心滚动图片2:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片2',
        产品中心滚动图片3:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片3',
        产品中心滚动图片4:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片4',
        产品中心滚动图片5:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片5',
        产品中心滚动图片6:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片6',
        产品中心滚动图片7:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片7',
        产品中心滚动图片8:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片8',
        产品中心滚动图片9:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片9',
        产品中心滚动图片10:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片10',
        产品中心滚动图片11:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片11',
        产品中心滚动图片12:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片12',
        产品中心滚动图片13:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片13',
        产品中心滚动图片14:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片14',
        产品中心滚动图片15:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片15',

        人民代表大会会议:'/mynews?ban_kuai=会议之窗&lan_mu=人民代表大会会议&tittle=默认',
        常委会会议:'/mynews?ban_kuai=会议之窗&lan_mu=常委会会议&tittle=默认',
        主任会议:'/mynews?ban_kuai=会议之窗&lan_mu=主任会议&tittle=默认',
        代表联系群众:'/mynews?ban_kuai=会议之窗&lan_mu=代表联系群众&tittle=默认',
        代表信箱:'/mynews?ban_kuai=会议之窗&lan_mu=代表信箱&tittle=默认',


        蓉城镇:'/mynews?ban_kuai=乡镇人大&lan_mu=蓉城镇&tittle=默认',
        木镇镇:'/mynews?ban_kuai=乡镇人大&lan_mu=木镇镇&tittle=默认',
        庙前镇:'/mynews?ban_kuai=乡镇人大&lan_mu=庙前镇&tittle=默认',
        陵阳镇:'/mynews?ban_kuai=乡镇人大&lan_mu=陵阳镇&tittle=默认',
        新河镇:'/mynews?ban_kuai=乡镇人大&lan_mu=新河镇&tittle=默认',
        丁桥镇:'/mynews?ban_kuai=乡镇人大&lan_mu=丁桥镇&tittle=默认',
        朱备镇:'/mynews?ban_kuai=乡镇人大&lan_mu=朱备镇&tittle=默认',
        杨田镇:'/mynews?ban_kuai=乡镇人大&lan_mu=杨田镇&tittle=默认',
        乔木乡:'/mynews?ban_kuai=乡镇人大&lan_mu=乔木乡&tittle=默认',
        酉华镇:'/mynews?ban_kuai=乡镇人大&lan_mu=酉华镇&tittle=默认',
        杜村乡:'/mynews?ban_kuai=乡镇人大&lan_mu=杜村乡&tittle=默认',
       
    };
    
}
export default (new AppGlobal());
