class AppGlobal {
    url = {
        login:'https://wx.wuminmin.top/qyrd/login',
        index:'/',
        tian_qi_xia_zai:'https://wx.wuminmin.top/qyrd/tian_qi_xia_zai',
        uploadimg:'https://wx.wuminmin.top/qyrd/upload_img',
        rd_xia_zai_tabs_by_ban_kuai:'https://wx.wuminmin.top/qyrd/rd_xia_zai_tabs_by_ban_kuai',
        rd_xia_zai_tabs_by_ban_kuai2:'https://wx.wuminmin.top/qyrd/rd_xia_zai_tabs_by_ban_kuai2',
        rd_updata:'https://wx.wuminmin.top/qyrd/rd_updata',
        rd_xia_zai:'https://wx.wuminmin.top/qyrd/rd_xia_zai',
        rd_xia_zai_by_lan_mu:'https://wx.wuminmin.top/qyrd/rd_xia_zai_by_lan_mu',
        rd_xia_zai_by_tittle:'https://wx.wuminmin.top/qyrd/rd_xia_zai_by_tittle',
        rd_xia_zai_time_by_tittle:'https://wx.wuminmin.top/qyrd/rd_xia_zai_time_by_tittle',
        get_header_menu_list_data:'https://wx.wuminmin.top/qyrd/get_header_menu_list_data',
        首页工程案例1:'https://wx.wuminmin.top/qyrd/image?id=新闻图片1',
        首页工程案例2:'https://wx.wuminmin.top/qyrd/image?id=新闻图片2',
        首页工程案例3:'https://wx.wuminmin.top/qyrd/image?id=新闻图片3',
        首页工程案例4:'https://wx.wuminmin.top/qyrd/image?id=新闻图片4',
        首页工程案例5:'https://wx.wuminmin.top/qyrd/image?id=新闻图片5',
        首页中间横幅图片1:'https://wx.wuminmin.top/qyrd/image?id=首页中间横幅图片1',
        首页中间横幅图片2:'https://wx.wuminmin.top/qyrd/image?id=首页中间横幅图片2',
        首页中间横幅图片3:'https://wx.wuminmin.top/qyrd/image?id=首页中间横幅图片3',
        产品中心滚动图片1:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片1',
        产品中心滚动图片2:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片2',
        产品中心滚动图片3:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片3',
        产品中心滚动图片4:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片4',
        产品中心滚动图片5:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片5',
        产品中心滚动图片6:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片6',
        产品中心滚动图片7:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片7',
        产品中心滚动图片8:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片8',
        产品中心滚动图片9:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片9',
        产品中心滚动图片10:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片10',
        产品中心滚动图片11:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片11',
        产品中心滚动图片12:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片12',
        产品中心滚动图片13:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片13',
        产品中心滚动图片14:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片14',
        产品中心滚动图片15:'https://wx.wuminmin.top/qyrd/image?id=产品中心滚动图片15',
       
    };
    
}
export default (new AppGlobal());
